---
user: morelli
git_name: "Marcos Morelli"
git_email: "marcos.eduardo.morelli@gmail.com"

downloads: ~/.ansible-downloads/

basic_dirs:
  - { path: "{{ lookup('env', 'HOME') }}/Git", 
      state: directory }

git_repos:
  - { name: dracula-iterm,
      repo: "https://github.com/dracula/iterm.git",
      dest: "~/Git/dracula" }

configure_dock: true
dockitems_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - System Preferences
  - TV
dockitems_persist:
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 1
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Slack"
    path: "/Applications/Slack.app"
    pos: 4

homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages:
  - git
  - go
  - jq
  - nvm
  - openssh
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - discord
  - docker
  - google-chrome
  - insomnia
  - iterm2
  - rectangle
  - slack
  - visual-studio-code
  - zoom

homebrew_fonts:
  - { name: font-fira-code }

iterm2_dynamic_profiles_local:
  - /Users/morelli/Git/marcosmorelli/ansible-dev-mac/files/iTerm-Profiles.json
iterm2_shell_integration: yes

node_versions_install:
  - 16

default_node_version: 16
