---
- name: Ensure iTerm directories are initialized if they are not already.
  command: "open -a /Applications/iTerm.app"
  args:
    creates: "~/Library/Application Support/iTerm2/DynamicProfiles/"

- name: Ensure local DynamicProfiles are copied to iTerm2 directory.
  copy:
    src: "{{ item }}"
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/{{ item | basename }}"
    remote_src: yes
    backup: no
  become: false
  with_items: "{{ iterm2_dynamic_profiles_local }}"

- name: Ensure shell integration is installed.
  shell: curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
  args:
    warn: no
  when: iterm2_shell_integration is defined and iterm2_shell_integration
